//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Saver.rc
//
#define IDS_DESCRIPTION                 1
#define IDS_SYSTEM_TRAY                 2
#define IDABOUT                         3
#define IDS_TITLE_CONFIGURATION         3
#define IDS_START_CLIENT                4
#define IDS_START_COMMAND_LINE_CLIENT   5
#define IDS_HOW_TO_FIND_FILE            6
#define IDS_HOW_TO_DOWNLOAD_JVM         7
#define IDS_SERVER_ERROR_OCCURRED       8
#define IDS_ERROR_OCCURRED              9
#define IDS_ERROR_OCCURRED_SEE_DETAILS  10
#define IDS_ERROR_OCCURRED_SEE_DETAILS_SERVICE 11
#define IDS_NOTE_SIZE_OF_WORK_UNIT      12
#define IDS_NO_ACTIVE_WORK_UNIT         13
#define IDS_CONFIG_SERVER               14
#define IDS_CHANGE_CONFIG_SERVER        15
#define IDS_PACKAGE_SIZE_INFO           16
#define IDS_TIMEFRAME_ENDS_AFTER_BEGINS 17
#define IDS_TF2_BEGINS_AFTER_TF1_ENDS   18
#define IDS_TF3_BEGINS_AFTER_TF2_ENDS   19
#define IDS_TEST_THIS_CONFIGURATION     20
#define IDS_TEST                        21
#define IDS_TEST_RUNNING                22
#define IDS_UPDATE_CLIENT               23
#define IDS_STOP_CONTROL_CENTER         24
#define IDS_CHANGE_LOCAL_CFG            25
#define IDS_PROCESSORS_SMALLER_1        26
#define IDS_JAVA_LIB                    27
#define IDS_CPU_USAGE_BETWEEN_0_100     28
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SAVER_DIALOG                102
#define IDS_SCREENSAVER                 102
#define IDS_FILE_NOT_EXISTS             103
#define IDS_ERROR                       104
#define IDS_FILE_NO_PERMISSION          105
#define IDS_STRING_INIT                 106
#define IDD_PROPPAGE_PROCESS            106
#define IDS_NAME_NOT_DEFINED            107
#define IDD_PROPPAGE_WORK_UNIT          107
#define IDS_PROCESSORS_PACKAGES_ERROR   108
#define IDS_PROCESSORS_GREATER_5        109
#define IDS_INFORMATION                 110
#define IDS_WORK_UNITS_GREATRER_5       111
#define IDS_WORK_UNITS_LESS_1           112
#define IDS_TEAMNAME_INFO               113
#define IDS_PLEASE_NOTE                 114
#define IDS_NAME_NOTE                   115
#define IDS_EMAIL_NOTE                  116
#define IDS_TEAM_NOTE                   117
#define IDD_STATE                       118
#define IDS_REMOVE_FILES                118
#define IDS_UNINSTALL                   119
#define IDS_CONNECTION                  120
#define IDS_NO_CONNECTION_RESTART       121
#define IDS_ACTIVATE_NEW_CONFIG         122
#define IDS_ACTIVATE_NEW_CONFIG_NOW     123
#define IDS_PREREQUISITE                124
#define IDS_REQUIRED_JAVA_VM            125
#define IDS_WARNING                     126
#define IDS_ALREADY_RUNNING             127
#define IDR_MAINFRAME                   128
#define IDS_SUCCESSFUL                  128
#define IDC_NULLCURSOR                  129
#define IDS_MESSAGE_INFO                129
#define IDS_MUST_BE_ONLINE              130
#define IDD_WAITFRAME                   131
#define IDS_TEST_INFO                   131
#define IDS_INSTALL_SUCCESSFUL          132
#define IDS_INSTALL_START_CONTROL_CENTER 133
#define IDS_INSTALL_COMPLETED_SUCCESSFULLY 134
#define IDS_INSTALL_CONTINUE            135
#define IDD_PROGRESS                    136
#define IDS_INSTALL                     136
#define IDS_INSTALL_SHORTCUT_STARTUP    137
#define IDS_EMAIL_NOT_VALID             138
#define IDS_OVERWRITE_FILE              139
#define IDS_OVERWRITE_WITH_NEW_CONFIG   140
#define IDD_DIALOG_JAVA_ERROR           150
#define IDD_DIALOG_PORT                 151
#define IDD_DIALOG_CONTROL_CENTER       153
#define IDD_DIALOG_INSTALL              154
#define IDR_MENU_CONTROL                155
#define IDD_PROPPAGE_GENERAL            155
#define IDD_PROPPAGE_OPTION             156
#define IDD_PROPPAGE_CONNECTION         157
#define IDD_PROPPAGE_POWER              158
#define IDD_PROPPAGE_LOGGING            159
#define IDB_ZETA                        160
#define IDR_POPUP_MENU                  167
#define IDD_DIALOG_LICENSE              182
#define IDD_PROPPAGE_SECURITY           183
#define IDC_EDIT_NAME                   1000
#define IDC_LIST_RANKING                1000
#define IDC_STATIC_LOCAL_PACKAGES       1001
#define IDC_EDIT_TEAMNAME               1001
#define IDC_PROGRESS_ACTIVE             1002
#define IDC_COMBO_PRIO                  1003
#define IDC_STATIC_CLOCK                1003
#define IDC_STATIC_ACTION               1004
#define IDC_STATIC_PERCENT              1005
#define IDC_CHECK_DISPLAY_ST            1006
#define IDC_STATIC_ACTION2              1007
#define IDC_EDIT_EMAIL                  1008
#define IDC_COMBO_PACKAGE_SIZE          1009
#define IDC_CHECK_DISPLAY_RANKING       1010
#define IDC_STATIC_RANKING_TEXT         1011
#define IDC_STATIC_CLOCK_LARGE          1012
#define IDC_EDIT_ROOT_PATH              1013
#define IDC_EDIT_JAVA_VM                1014
#define IDC_BUTTON_VM_CHOOSE            1015
#define IDC_BUTTON_ROOT_BROWSE          1016
#define IDC_BUTTON_TEST                 1017
#define IDC_EDIT_JAVA_LIB               1017
#define IDC_EDIT_PROZESSOREN            1018
#define IDC_BUTTON_LIB_CHOOSE           1018
#define IDC_BUTTON_HOME                 1019
#define IDC_COMBO_INTENSITY             1020
#define IDC_COMBO_TASK_NAME             1021
#define IDC_EDIT_PACKAGES               1022
#define IDC_BUTTON_HELP                 1023
#define IDC_BUTTON_NOTE_NAME            1024
#define IDC_BUTTON_NOTE_EMAIL           1025
#define IDC_BUTTON_NOTE_TEAMNAME        1026
#define IDC_STATIC_ERROR                1027
#define IDC_BUTTON_NOTE_NUMBER_OF_WORK_UNITS 1027
#define IDC_CHECK_USE_PROXY             1028
#define IDC_BUTTON_NOTE_SIZE_OF_WORK_UNIT 1028
#define IDC_EDIT_PROXY_ADDRESS          1029
#define IDC_EDIT_PROXY_PORT             1030
#define IDC_STATIC_PROXY_ADDRESS        1031
#define IDC_STATIC_PROXY_PORT           1032
#define IDC_EDIT_PORT_NUMBER            1033
#define IDC_BUTTON_TRANSFER_WU          1034
#define IDC_STATIC_FINISHED_WU          1035
#define IDC_STATIC_CURRENT_STATUS       1037
#define IDC_STATIC_PROGRESS             1038
#define IDC_RADIO_MODE_SERVICE          1039
#define IDC_RADIO_MODE_SCREEN_SAVER     1040
#define IDC_PROGRESS1                   1041
#define IDC_STATUS                      1042
#define IDC_STATIC_PERFORMANCE          1043
#define IDC_STATIC_ACTIVE_THREADS       1044
#define IDC_COMBO_THREAD_ID             1045
#define IDC_STATIC_THREAD_ID            1046
#define IDC_STATIC_REMAINING            1047
#define IDC_CHECK_TEAM                  1048
#define IDC_COMBO_RESOURCES             1049
#define IDC_CHECK_MESSAGES              1051
#define IDC_BUTTON_HIDE                 1052
#define IDC_CHECK_SYSTEM_TRAY           1053
#define IDC_SLIDER_CPU_USAGE            1058
#define IDC_STATIC_PRIORITY             1059
#define IDC_RADIO_MODE_COMMAND_LINE     1060
#define IDC_STATIC_JAVA_LIB             1061
#define IDC_STATIC_ERROR2               1062
#define IDC_STATIC_ERROR3               1063
#define IDC_CHECK_SHORTCUT              1064
#define IDC_CHECK_START_CLIENT          1065
#define IDC_CHECK_START_CONTROL_CENTER  1066
#define IDC_CHECK_PROXY_AUTHENTICATION  1067
#define IDC_STATIC_USERNAME             1068
#define IDC_EDIT_USERNAME               1069
#define IDC_STATIC_PASSWORD             1070
#define IDC_EDIT_PASSWORD               1071
#define IDC_ASYNCHRONOUS_TRANSFER       1072
#define IDC_TRANSFER_DETECT             1073
#define IDC_STATIC_TRANSFER_DETECT      1074
#define IDC_CHECK_CONNECTION_TO_SERVER  1075
#define IDC_BATTERY_MODE                1078
#define IDC_DATETIMEPICKER_MO1          1079
#define IDC_DATETIMEPICKER_MO2          1080
#define IDC_CHECK_CMD_CONTROL_CENTER_STARTUP 1080
#define IDC_DATETIMEPICKER_TU1          1081
#define IDC_CHECK_SERVICE_CONTROL_CENTER_STARTUP 1081
#define IDC_CHECK_STD_OUTPUT            1081
#define IDC_DATETIMEPICKER_TU2          1082
#define IDC_EDIT_EVENT_LOG_FILE         1082
#define IDC_DATETIMEPICKER_WE1          1083
#define IDC_EDIT_EVENT_FORMAT_TIMESTAMP 1083
#define IDC_DATETIMEPICKER_WE2          1084
#define IDC_EDIT_EVENT_LOG_FILE_SIZE    1084
#define IDC_DATETIMEPICKER_TH1          1085
#define IDC_EDIT_EVENT_NUMBER_BACKUP    1085
#define IDC_COMPLETE_ALL_LOCAL_WU       1085
#define IDC_DATETIMEPICKER_TH2          1086
#define IDC_VALUES_CHANGED_AT_SERVER    1086
#define IDC_DATETIMEPICKER_FR1          1087
#define IDC_BUTTON_CHANGE_AT_SERVER     1087
#define IDC_DATETIMEPICKER_FR2          1088
#define IDC_EDIT_LICENSE                1088
#define IDC_DATETIMEPICKER_SA1          1089
#define IDC_ENCRYPTS_URL                1089
#define IDC_DATETIMEPICKER_SA2          1090
#define IDC_EDIT_TRUSTED_USERS          1090
#define IDC_DATETIMEPICKER_SU1          1091
#define IDC_TRUST_ALL_USER              1091
#define IDC_DATETIMEPICKER_SU2          1092
#define IDC_CPU_USAGE_MO1               1093
#define IDC_CPU_USAGE_MO2               1094
#define IDC_CPU_USAGE_MO3               1095
#define IDC_CPU_USAGE_TU1               1096
#define IDC_CPU_USAGE_WE1               1097
#define IDC_CPU_USAGE_TH1               1099
#define IDC_CPU_USAGE_FR1               1100
#define IDC_CPU_USAGE_SA1               1101
#define IDC_CPU_USAGE_SU1               1102
#define IDC_CPU_USAGE_TU2               1103
#define IDC_CPU_USAGE_WE2               1104
#define IDC_CPU_USAGE_TH2               1105
#define IDC_CPU_USAGE_FR2               1106
#define IDC_DATETIMEPICKER_MO3          1107
#define IDC_DATETIMEPICKER_MO4          1108
#define IDC_DATETIMEPICKER_TU3          1109
#define IDC_DATETIMEPICKER_TU4          1110
#define IDC_DATETIMEPICKER_WE3          1111
#define IDC_DATETIMEPICKER_WE4          1112
#define IDC_DATETIMEPICKER_TH3          1113
#define IDC_DATETIMEPICKER_TH4          1114
#define IDC_DATETIMEPICKER_FR3          1115
#define IDC_DATETIMEPICKER_FR4          1116
#define IDC_DATETIMEPICKER_SA3          1117
#define IDC_DATETIMEPICKER_SA4          1118
#define IDC_DATETIMEPICKER_SU3          1119
#define IDC_DATETIMEPICKER_SU4          1120
#define IDC_DATETIMEPICKER_MO5          1121
#define IDC_DATETIMEPICKER_MO6          1122
#define IDC_DATETIMEPICKER_TU5          1123
#define IDC_DATETIMEPICKER_TU6          1124
#define IDC_DATETIMEPICKER_WE5          1125
#define IDC_DATETIMEPICKER_WE6          1126
#define IDC_DATETIMEPICKER_TH5          1127
#define IDC_DATETIMEPICKER_TH6          1128
#define IDC_DATETIMEPICKER_FR5          1129
#define IDC_DATETIMEPICKER_FR6          1130
#define IDC_DATETIMEPICKER_SA5          1131
#define IDC_DATETIMEPICKER_SA6          1132
#define IDC_DATETIMEPICKER_SU5          1133
#define IDC_DATETIMEPICKER_SU6          1134
#define IDC_CPU_USAGE_SA2               1135
#define IDC_CPU_USAGE_SU2               1136
#define IDC_CPU_USAGE_TU3               1137
#define IDC_CPU_USAGE_WE3               1138
#define IDC_CPU_USAGE_TH3               1139
#define IDC_CPU_USAGE_FR3               1140
#define IDC_CPU_USAGE_SA3               1141
#define IDC_CPU_USAGE_SU3               1142
#define ID_UNINSTALL_UNISTALL           40001
#define ID_CONFIG_CONFIG                40002
#define ID_WEB_HOME                     40003
#define ID_WEB_NEWS                     40004
#define ID_WEB_STATISTIC                40005
#define ID_HELP_FAQ                     40006
#define ID_HELP_ABOUT                   40007
#define ID_HELP_FORUM                   40008
#define ID_WEB_STATISTIC_DETAIL         40009
#define ID_WEB_TEAMMEMBERS              40010
#define ID_CLOSE                        40011
#define ID_VIEW                         40012
#define ID_SERVER_CONFIG                40013
#define IDD_ACTIONS_TRANSFER_WORK_UNITS 40014
#define IDD_ACTIONS_STOP_COMPUTATION    40015
#define IDD_ACTIONS_RESTART_COMPUTATION 40016
#define ID_RESTART_COMPUTATION          40017
#define ID_STOP_COMPUTATION             40018
#define ID_LOG_VIEW_INFORMATION_LOG     40019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         40020
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
